### ISSUE TITLE
sentence-transformers conda version outdated

### ISSUE THREAD

**Issue by nreimers** [conda-forge/sentence-transformers-feedstock#17]
Hi,
the [sentence-transformers](https://github.com/UKPLab/sentence-transformers/releases) version in conda-forge is at version 0.4.1, which is quite outdated.

The most recent version is 1.2.0: https://github.com/UKPLab/sentence-transformers/releases

I have seen that the last pull requests (#14 #15 #16) have not been merged yet.

Is there a way to update the version at conda forge to the most recent 1.2.0 version of sentence-transformers?

Best
Nils

**Comment by nreimers** [comment]
Marking the prev. reviewers  @ndmaxar @oblute @rluria14 

Let me know if there is some way how I can help to update the conda-forge version of sentence-transformers.

**Comment by nreimers** [comment]
Hi  @ndmaxar @oblute @rluria14

Any updates? Would be great if sentence-transformers version in conda forge could be updated. It is still at 0.4.1, while sentence-transformers version 2 is already available.

**Comment by oblute** [comment]
It is done now, and up-to-date. PRs are always welcome!

**Comment by nreimers** [comment]
Hi @oblute 
Great, thanks for merging them.

If I understand the system correctly, PRs are created automatically when the version on pip changes? Or do I have to trigger it somehow?
